name: flutter_utils
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  get: ^4.1.4
  flutter_bloc: ^7.0.1
  path_provider: ^2.0.2
  platform: ^3.0.0
  video_player: ^2.1.10
  chewie: ^1.2.2
  responsive_framework: ^0.1.4
  uuid: ^3.0.4
  shared_preferences: ^2.0.6
  flutter_slider_drawer: ^2.0.0
  permission_handler: ^8.1.3
  bot_toast: ^4.0.1
  archive: ^3.1.2
  webview_flutter: ^2.0.10
  jaguar_flutter_asset: ^3.0.0
  timeline_tile: ^2.0.0
  flutter_swiper_null_safety: ^1.0.2
  cached_network_image: ^3.1.0
  octo_image: ^1.0.0+1
  flutter_html: ^2.1.1
  font_awesome_flutter: ^9.1.0
  editable: ^2.0.0
  syncfusion_flutter_datagrid: ^19.2.51-beta

  audioplayers:
    path: ./plugins/audioplayers-0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
