name: flutter_utils
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # 请求
  dio: ^4.0.0
  # 路由
  get: ^4.1.4
  # 状态管理
  flutter_bloc: ^7.0.1
  # 本地路径
  path_provider: ^2.0.2
  # 视频播放
  video_player: ^2.1.10
  # 视频播放
  chewie: ^1.2.2
  uuid: ^3.0.4
  # 缓存
  shared_preferences: ^2.0.6
  # 权限
  permission_handler: ^8.1.3
  # 提示
  bot_toast: ^4.0.1
  # 解压/压缩
  archive: ^3.1.2
  webview_flutter: ^2.0.10
  # 时间轴
  timeline_tile: ^2.0.0
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  # 图片缓存
  cached_network_image: ^3.1.0
  # 加载html
  flutter_html: ^2.1.1
  # 图标
  font_awesome_flutter: ^9.1.0
  # 表格
  editable: ^2.0.0
  # 表格
  syncfusion_flutter_datagrid: ^19.2.51-beta
  # 打开第三方软件
  url_launcher: ^6.0.9
  # 图片预览
  photo_view: ^0.12.0
  # 分享
  share_plus: ^2.1.4
  # APP信息
  package_info: ^2.0.2
  # 打开系统设置
  open_app_settings: ^2.0.0
  # 侧滑抽屉
  flutter_slider_drawer: ^2.0.0
  # 刷新加载
  flutter_easyrefresh: ^2.2.1
  # 加载动画
  flutter_spinkit: ^5.0.0
  # 启动白屏
  flutter_splash_screen: ^0.3.0
  # 索引列表
  azlistview: ^2.0.0-nullsafety.0
  # 媒体播放器
  fijkplayer: ^0.10.0
  # 打开文件
  open_file: ^3.2.1
  # 瀑布流布局
  flutter_staggered_grid_view: ^0.4.0
  # android设置壁纸
  wallpaper_manager_flutter: ^0.0.2
  # 日期选择器
  syncfusion_flutter_datepicker: ^19.2.56
  # json to Dart
  json_annotation: ^4.0.1
  # 加密
  crypto: ^3.0.1
  # 自适应
  flutter_screenutil: ^5.0.0+2
  extended_nested_scroll_view: ^4.0.0
  # 提取图片突出色
  palette_generator: ^0.3.0
  # 获取设备信息
  device_info: ^2.0.2
  # 工具库
  flustars: ^2.0.1
  # 设置界面UI
  settings_ui: ^1.0.0

  audioplayers:
    path: ./plugins/audioplayers-0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json to Dart
  build_runner: ^2.0.0
  json_serializable: ^4.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/h5/
    - assets/images/
