name: flutter_utils
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  get: ^4.1.4
  flutter_bloc: ^7.0.1
  path_provider: ^2.0.2
  platform: ^3.0.0
  video_player: ^2.1.10
#  flutter_sound: ^8.2.0
  chewie: ^1.2.2
  responsive_framework: ^0.1.4
  uuid: ^3.0.4
  shared_preferences: ^2.0.6
  hidden_drawer_menu: ^3.0.0
  flutter_slider_drawer: ^2.0.0
  settings_ui: ^1.0.0
  permission_handler: ^8.1.3
  bot_toast: ^4.0.1
  archive: ^3.1.2
  webview_flutter: ^2.0.10
  jaguar_flutter_asset: ^3.0.0

  flutter_sound:
    path: ./plugins/flutter_sound-8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
